// Museum content. Chinese copy is verbatim from hantianwu.com; English is a translation.
(function () {
const T = (en, zh) => ({ en, zh });

const S = (id, label, heading, lede, body, images) => ({ id, label, heading, lede, body, images: images || [] });

const LAB = {
  background: T("Background", "背景"),
  research: T("Pain points, needs & scenarios", "前期用户痛点、需求与场景分析"),
  solution: T("Solution design", "方案设计"),
  build: T("Technical implementation", "技术实现"),
  validation: T("Testing & validation", "测试与验证"),
  limits: T("Limitations & next steps", "局限与下一步"),
};

const PROJECTS = {
  talevision: {
    hall: "research", wall: "left", plate: "#1f3a6b", num: "01", theme: "#6fb3dd", slideFrame: "16 / 9",
    tagline: T("An AI-assisted tactile graphics product for language and cognitive education for children with visual impairments", "面向视障儿童语言与认知教育的 AI 辅助触觉图形产品"),
    year: "2024",
    kicker: T("Inclusive AI · Graduation project", "包容性 AI · 毕业设计"),
    title: T("TaleVision", "TaleVision 点视机"),
    sub: T("点视机", ""),
    standfirst: T(
      "An AI learning device that turns language into touchable images and sound, exploring multisensory cognitive support for children with visual impairments.",
      "把语言转为可触摸图像与声音的 AI 学习教具，探索视障儿童的多感官认知支持。"),
    audience: T("A child, a parent with a white cane, a teacher listening", "触摸墙面的孩子、持盲杖的家长、戴耳机的老师"),
    role: T("Product, interaction and research design", "产品、交互与研究设计"),
    collab: T("Individual graduation project", "个人毕业设计"),
    methods: [T("Inclusive design", "包容性设计"), T("User research", "用户研究"), T("AI prototyping", "AI 原型")],
    results: [
      T("A working software and hardware prototype", "完成软硬件交互原型"),
      T("A defined language-to-tactile-image workflow", "定义语言到触觉图像的工作流"),
      T("Paper published in the International Journal of Human–Computer Studies", "论文发表于《International Journal of Human–Computer Studies》"),
    ],
    hero: { src: "img/web/tv-hero.jpg", ratio: "2 / 1", pos: "50% 92%", crop: true, caption: T("TaleVision in a home study setting", "家庭自学场景中的点视机") },
    marks: [
      { x: 7, y: 40, w: 15, h: 24, c: "#e6b053" },
      { x: 27.3, y: 30, w: 5, h: 6.5, c: "#bcd8b4" },
      { x: 27.3, y: 41, w: 4.4, h: 6.5, c: "#6d5090" },
      { x: 27.3, y: 52, w: 3.6, h: 5, c: "#c74a33" },
    ],
    sections: [
      S("background", LAB.background,
        T("Making language tangible", "让语言有形"),
        T("Without visual input, it is harder to build a link between the shape of an object and the meaning of a word.",
          "视觉输入缺失会使物体形态与词义的联系更难建立。"),
        T("Starting from the language cognition and braille learning of children with visual impairments, I focused on the shortage of teaching aids, the limits of tactile expression, and the single channel of learning feedback.",
          "我从视障儿童的语言认知与盲文学习出发，聚焦教具不足、触觉表达有限和学习反馈单一的问题。")),
      S("research", LAB.research,
        T("Research evidence", "研究证据"),
        T("Literature, school fieldwork and evaluation together set the boundaries of the design.",
          "文献、学校调研和评估共同界定了设计边界。"),
        T("During fieldwork at Shanghai School for the Blind I observed that braille learning can bring boredom and forgetting, and that existing teaching aids offer limited intelligence and multisensory support.",
          "在上海市盲童学校的调研中，我观察到盲文学习可能带来厌烦和遗忘，现有教具的智能化与多感官支持也较有限。"),
        [{ src: "img/web/tv-field-1.jpg", ratio: "3 / 2",
           caption: T("Observation and interviews to understand real learning settings", "线下观察与访谈帮助理解真实学习场景") },
         { src: "img/slides/talevision/11.jpg", ratio: "3 / 2",
           caption: T("Goals, pain points and needs of children and teachers", "儿童与教师的目标、痛点和需求") }]),
      S("solution", LAB.solution,
        T("A multimodal design judgement", "多模态设计判断"),
        T("Touch, voice and generated images are organised into one continuous path of exploration.",
          "触觉、语音与生成图像被组织为连续的探索路径。"),
        T("After a child reads braille aloud, the system turns speech into an image and audio; the image is binarised and granulated, then presented as tactile dots that carry cues about form.",
          "用户朗读盲文后，系统将语音转为图像与音频；图像经二值化和颗粒化处理后，以触点呈现形态线索。"),
        [{ src: "img/web/tv-scene-2.jpg", ratio: "3 / 4", fit: "contain",
           caption: T("Speech, AI image and tactile output form one continuous chain", "语音、AI 图像与触觉输出形成连续链路") },
         { src: "img/web/tv-scene-3.jpg", ratio: "3 / 4", fit: "contain",
           caption: T("The product imagined in home, classroom and after-school use", "产品在家中自学、学校教室与课外生活中的使用设想") }]),
      S("build", LAB.build,
        T("Building the prototype", "原型实现"),
        T("A software and hardware prototype tests the chain from generated content to tactile output.",
          "软硬件原型验证生成内容到触觉输出的链路。"),
        T("The physical prototype drives its dots with a 3D-printed structure, an Arduino relay array and miniature electromagnets; the generation side trialled DALL·E 3, with a software pipeline handling the content conversion.",
          "实体原型以 3D 打印结构、Arduino 多路继电器和微型电磁铁控制触点；生成端试用 DALL·E 3，并用软件流程处理内容转换。"),
        [{ src: "img/web/tv-render-1.png", ratio: "4 / 3", fit: "contain",
           caption: T("Structure of the graphic area, braille area, voice and page controls", "图形区、盲文区、语音与翻页控制的结构定义") },
         { src: "img/web/tv-keyboard.png", ratio: "4 / 3", fit: "contain",
           caption: T("Control surface and key layout", "控制面与按键布局") },
         { src: "img/web/tv-dims.jpg", ratio: "4 / 3", fit: "contain", treat: "halftone",
           caption: T("Hardware dimensions", "硬件尺寸") }]),
      S("validation", LAB.validation,
        T("Validation and outcome", "验证与产出"),
        T("Testing confirmed the direction of the prototype and recorded where it needs to improve.",
          "测试验证了原型方向，也记录了进一步改进点。"),
        T("Five sighted children and 14 children with congenital visual impairments tested the product. Almost all participants reported high satisfaction and rated the user experience highly; we also observed how children and teachers interacted with it, to improve teaching and learning.",
          "五位明眼儿童和 14 位先天视障儿童参与了产品测试。几乎所有参与者都表示满意度较高，并对使用体验给出了较高评价；我们也观察了儿童与教师的互动方式，以改进教学与学习。"),
        [{ src: "img/web/tv-test-1.jpg", ratio: "4 / 3",
           caption: T("A participant testing the tactile prototype", "参与者测试触觉原型") },
         { src: "img/web/tv-test-2.jpg", ratio: "4 / 3",
           caption: T("Reading the generated tactile image by hand", "以手阅读生成的触觉图像") },
         { src: "img/web/tv-test-3.jpg", ratio: "4 / 3",
           caption: T("Feedback session on the tactile presentation", "关于触觉呈现的反馈记录") }]),
      S("limits", LAB.limits,
        T("Limitations and next steps", "局限与下一步"),
        T("This is a feasibility study, not a conclusion about long-term learning effect.",
          "这是一项可行性探索，不是长期学习效果的结论。"),
        T("Generation performs weakly on complex objects and on lines of poetry, and two-dimensional dots struggle to express three-dimensional form; the next steps are to improve stability, to explore tactile expression with varying height, and to evaluate over time in real learning settings.",
          "复杂物体和诗句的生成表现较弱，二维触点也难以表达立体形态；下一步应提升稳定性、探索高度变化的触觉表达，并在真实学习场景中长期评估。")),
    ],
    figures: [
      { x: 4.5, y: 3, u: 2.05, coat: "#f0d79a", legs: "#5b7cb0", hair: "#2d2b2b", acc: "hand" },
      { x: 11.5, y: 1.5, u: 3.15, coat: "#9db39f", legs: "#efeee9", hair: "#2d2b2b", acc: "cane" },
      { x: 18.5, y: 2.5, u: 3.05, coat: "#8fb0d2", legs: "#e6d9b8", hair: "#d7d3d3", acc: "phones" },
    ],
  },

  mirrorcle: {
    hall: "research", wall: "center", plate: "#dfe4ea", num: "02", fitWidth: true, theme: "#74b6b9",
    tagline: T("A facial-expression recognition and training app for children with autism", "面向自闭症儿童的表情识别与训练应用"),
    year: T("2022–2023", "2022–2023"),
    kicker: T("Children's interaction · Emotion cognition", "儿童交互 · 情绪认知"),
    title: T("Mirrorcle", "镜遇 Mirrorcle"),
    standfirst: T(
      "A prototype for expression-recognition training that combines an interactive picture book, a live animated mirror and a practice flow.",
      "将互动绘本、实时动画镜像和练习流程结合的表情认知训练原型。"),
    audience: T("Five children sitting on the floor", "坐在地上的五个孩子"),
    role: T("Research, interaction design and prototyping", "调研、交互设计与原型制作"),
    collab: T("A six-person course design team", "6 人课程设计团队"),
    methods: [T("Children's interaction", "儿童交互"), T("User research", "用户研究"), T("Prototype iteration", "原型迭代")],
    results: [
      T("An interactive picture book and mirror prototype", "完成交互绘本与镜像原型"),
      T("The flow iterated through two rounds of prototype testing", "经过两轮原型测试迭代流程"),
      T("Clear needs for accompanied use and a simplified interface", "明确陪同使用与界面简化需求"),
    ],
    hero: { ph: T("Mirrorcle cover — teal device and emotion practice graphics", "镜遇封面 — 青绿色设备与情绪练习图形"), ratio: "16 / 10",
            caption: T("Interactive picture book and mirror practice", "互动绘本与镜像练习") },
    marks: [
      { x: 41.5, y: 38, w: 10, h: 20, c: "#c74a33" },
      { x: 55, y: 42, w: 6.5, h: 11, c: "#e6b053" },
      { x: 55.5, y: 58, w: 3.2, h: 5.5, c: "#bcd8b4" },
    ],
    sections: [
      S("background", LAB.background,
        T("Understanding and practising expressions", "理解和练习表情"),
        T("The project explores an experience of expression recognition and imitation practice for children with autism.",
          "项目探索面向自闭症儿童的表情认知与模仿练习体验。"),
        T("The research looked at the difficulties children may meet in understanding a situation, recognising an expression and expressing emotion, and brought the everyday company of families and teachers into the design scenario.",
          "研究关注儿童在理解情境、识别表情和表达情绪时可能遇到的困难，并把家庭与教师的日常陪伴纳入设计场景。")),
      S("research", LAB.research,
        T("Research and personas", "调研与人物模型"),
        T("Literature, expert conversations and observation in charity classrooms formed the design input.",
          "文献、专家交流和公益课堂观察共同形成设计输入。"),
        T("The team turned research at rehabilitation institutions and consultation with therapists and experts into personas and needs: content has to stay close to daily life, steps have to be clear, and room has to be left for a teacher or parent to help.",
          "团队把康复机构调研、治疗师及专家咨询转化为人物模型和需求：内容需要贴近日常、步骤要清晰，并为教师或家长留出辅助空间。"),
        [{ src: "img/slides/mirrorcle/02.jpg", ratio: "3 / 2",
           caption: T("Desk research, expert interviews and the insights drawn from them", "文献研究、专家访谈，以及由此得出的洞察") }]),
      S("solution", LAB.solution,
        T("Introducing the mirror through story", "以故事引入镜像"),
        T("An everyday scene gives context first, then guides observation and imitation.",
          "日常场景先提供语境，再引导观察和模仿。"),
        T("We used an interactive picture book to introduce situations of happiness, sadness, fear and anger, and gave feedback on expression through a live animated avatar, lowering the strangeness of facing a real mirror directly.",
          "我们选用互动绘本引入开心、难过、害怕和生气等情境，并以实时动画头像反馈表情，降低直接面对真实镜像的陌生感。"),
        [{ src: "img/slides/mirrorcle/03.jpg", ratio: "3 / 2",
           caption: T("Persona, brainstorm, paper prototype and the hardware choice", "人物模型、头脑风暴、纸原型与硬件选型") }]),
      S("build", LAB.build,
        T("From paper to a working prototype", "纸面到程序原型"),
        T("The prototype kept converging on content, learning pace and interface hierarchy.",
          "原型在内容、学习节奏和界面层级上持续收敛。"),
        T("The team made a paper prototype first and took in early feedback, then completed a working prototype; I took part in the research, interaction design and prototyping, working with the team to connect the picture book, the practice and the animated feedback.",
          "团队先制作纸原型并吸收初步反馈，再完成程序原型；我参与调研、交互设计与原型制作，协同团队推进绘本、练习和动画反馈的串联。"),
        [{ src: "img/slides/mirrorcle/04.jpg", ratio: "16 / 10",
           caption: T("Picture book, practice and animated feedback connected", "绘本、练习与动画反馈的串联") }]),
      S("validation", LAB.validation,
        T("Two rounds of testing and iteration", "两轮测试与迭代"),
        T("Testing was used to find problems in the flow, not to prove a therapeutic effect.",
          "测试用于发现流程问题，不作为疗效证明。"),
        T("Two rounds of prototype testing showed that some children were drawn to buttons or animation and mis-tapped or lost attention; the team therefore changed the learning to complete one emotion before moving to the next, and reduced the controls that interfere with attention.",
          "两轮原型测试显示，部分儿童会被按钮或动画吸引而误触或分心；团队据此将学习改为单个情绪完成后再进入下一项，并减少会干扰注意力的控件。")),
      S("limits", LAB.limits,
        T("Reading the results carefully", "谨慎解释结果"),
        T("Short, small-sample testing cannot replace long-term professional assessment.",
          "短时、小样本测试不能替代长期专业评估。"),
        T("The teacher group's records were incomplete and the number of teaching sessions was limited; future work should run longer assessment with informed consent and professional accompaniment, extend the story content, and keep reducing mis-taps and attention load.",
          "教师组的记录并不完整，且教学次数有限；未来应在知情同意和专业陪同下开展更长期的评估，扩展故事内容，并继续降低误触和注意力负担。")),
    ],
    figures: [
      { x: 36, y: 8, u: 1.55, coat: "#5b7cb0", legs: "#8a6b4a", hair: "#2d2b2b", sit: true },
      { x: 44, y: 5.5, u: 1.6, coat: "#efeee9", legs: "#2d2b2b", hair: "#2d2b2b", sit: true },
      { x: 52, y: 7, u: 1.55, coat: "#c74a33", legs: "#e6d9b8", hair: "#2d2b2b", sit: true },
      { x: 57.5, y: 3.5, u: 1.5, coat: "#dcd8d0", legs: "#8fb0d2", hair: "#2d2b2b", sit: true },
      { x: 63.5, y: 7, u: 1.6, coat: "#e6b053", legs: "#2d2b2b", hair: "#2d2b2b", sit: true },
    ],
  },

  hermoony: {
    hall: "research", wall: "right", plate: "#5a3a72", num: "03", theme: "#724c93",
    tagline: T("Design research on a multisensory VR therapeutic system for menstrual pain management", "面向女性经期疼痛管理的多感官 VR 疗愈系统设计研究"),
    year: "2026",
    kicker: T("Health experience · Multisensory VR", "健康体验 · 多感官 VR"),
    title: T("HerMoony", "HerMoony"),
    standfirst: T(
      "A multisensory interaction concept around the experience of menstrual pain, combining a companion agent with a VR relaxation flow.",
      "围绕经期疼痛体验的多感官交互概念，结合陪伴式 Agent 与 VR 放松流程。"),
    audience: T("Three women standing at the wall", "站在墙前的三位女性"),
    role: T("User research and interaction design", "用户研究与交互设计"),
    collab: T("Team design project", "团队设计项目"),
    methods: [T("Health design", "健康设计"), T("Experience strategy", "体验策略"), T("VR prototyping", "VR 原型")],
    results: [
      T("3 user interviews and 52 questionnaire responses", "完成 3 位用户访谈与 52 份问卷"),
      T("A defined multisensory service system", "定义多感官服务系统"),
      T("An experience experiment plan", "制定体验实验计划"),
    ],
    hero: { ph: T("HerMoony multisensory healing system concept", "HerMoony 多感官疗愈系统概念"), ratio: "16 / 10",
            caption: T("A support concept for the experience of menstrual pain", "经期疼痛体验支持概念") },
    marks: [
      { x: 77, y: 39, w: 13, h: 22, c: "#e6b053" },
      { x: 89, y: 45, w: 4, h: 7.5, c: "#6d5090" },
      { x: 92.5, y: 55, w: 3.2, h: 4, c: "#bcd8b4" },
      { x: 95, y: 53, w: 2.6, h: 5.5, c: "#c74a33" },
    ],
    sections: [
      S("background", LAB.background,
        T("An experience of pain that gets overlooked", "被忽略的疼痛体验"),
        T("The project looks at the experience of menstrual pain, where physical discomfort, emotional pressure and daily arrangements are tangled together.",
          "项目关注经期疼痛中身体不适、情绪压力与日常安排交织的体验。"),
        T("The design does not reduce menstrual pain to a single symptom; it treats it as a personal experience that needs to be understood, expressed and planned around.",
          "设计不把经期疼痛简化为单一症状，而是将其视作需要被理解、表达和安排的个人体验。")),
      S("research", LAB.research,
        T("Research input", "研究输入"),
        T("Small-sample interviews and a questionnaire were used to find experience opportunities, not to infer general clinical conclusions.",
          "小样本访谈与问卷用于识别体验机会，而非推断普遍临床结论。"),
        T("The team interviewed 3 relevant users and collected 52 questionnaire responses, and drew out needs around communicating pain, emotional company, and controllable ways to relax.",
          "团队访谈了 3 位相关用户并收集 52 份问卷回答，梳理出对疼痛沟通、情绪陪伴和可控放松方式的需求。"),
        [{ src: "img/slides/hermoony/10.jpg", ratio: "3 / 2",
           caption: T("Interviews and questionnaires settled into design input", "访谈和问卷沉淀为设计输入") }]),
      S("solution", LAB.solution,
        T("System judgement", "系统判断"),
        T("We designed company, environment and pace as layers of support the user can choose.",
          "我们把陪伴、环境和节奏设计成可选择的支持层。"),
        T("The system uses an agent as the entry point for conversation and guidance, and combines vision, sound and immersive environment into an adjustable flow, rather than replacing personal preference with a single solution.",
          "系统以 Agent 作为对话和引导入口，并将视觉、声音与沉浸环境组合为可调节的流程，避免以单一方案替代个人偏好。"),
        [{ src: "img/slides/hermoony/15.jpg", ratio: "3 / 2",
           caption: T("The agent and the immersive environment working together", "Agent 与沉浸环境协同") }]),
      S("build", LAB.build,
        T("Experience prototype", "体验原型"),
        T("The prototype connects agent guidance with VR scene changes.",
          "原型连接了 Agent 引导与 VR 场景切换。"),
        T("The team built the interaction flow from expressing a state, through companion guidance, to a VR relaxation scene, using multisensory cues to carry the atmosphere of each stage.",
          "团队构建从状态表达、陪伴式引导到 VR 放松场景的交互流程，并用多感官线索表达不同阶段的体验氛围。"),
        [{ src: "img/slides/hermoony/16.jpg", ratio: "16 / 10",
           caption: T("From state to guidance to immersive scene", "从状态表达到引导，再到沉浸场景") }]),
      S("validation", LAB.validation,
        T("The experiment plan", "实验计划"),
        T("The experiment is designed to evaluate how understandable the experience is and how it feels to use.",
          "实验被设计为评估体验可理解性与使用感受。"),
        T("We set out a plan for a prototype experience experiment, focused on whether users can understand the flow, choose the sensory cues that suit them, and give feedback on the way company is offered.",
          "我们制定了原型体验实验计划，关注用户是否能理解流程、选择适合自己的感官线索，并表达对陪伴方式的反馈。"),
        [{ src: "img/slides/hermoony/23.jpg", ratio: "3 / 2",
           caption: T("Focused on understanding and feedback", "以体验理解与反馈为重点") }]),
      S("limits", LAB.limits,
        T("The boundary of health design", "健康设计边界"),
        T("The concept is meant to support an experience; it does not replace medical advice or treatment.",
          "概念旨在支持体验，不替代医疗建议或治疗。"),
        T("The sample and the scope of validation are limited; further work needs relevant professionals to review content safety, accessibility and long-term effects together with us, and must leave users in control of exiting and adjusting at any time.",
          "样本与验证范围有限，后续需要与相关专业人士共同审查内容安全性、可及性和长期使用影响，并让用户保有随时退出与调整的控制权。")),
    ],
    figures: [
      { x: 78, y: 2.5, u: 3.1, coat: "#efeee9", legs: "#3b4a63", hair: "#2d2b2b", acc: "bag" },
      { x: 85.5, y: 1.5, u: 3.25, coat: "#c74a33", legs: "#c74a33", hair: "#8a5a3a" },
      { x: 92, y: 2.5, u: 3.05, coat: "#efeee9", legs: "#5c6046", hair: "#2d2b2b" },
    ],
  },

  huizhangbao: {
    hall: "commercial", wall: "left", plate: "#26406d", num: "04", fitWidth: true, theme: "#f8b452",
    year: "2023",
    kicker: T("Internet product · Bookkeeping experience", "互联网产品 · 记账体验"),
    title: T("Huizhangbao", "慧账宝"),
    standfirst: T(
      "Smart financial management software for university students, made with Ant Group: market and user research carried through to the information flow, the key tasks and the product interface.",
      "面向大学生的智慧财务管理软件，与蚂蚁集团合作完成：从市场与用户研究出发，落到信息流、关键任务与产品界面。"),
    audience: T("Two visitors reading the ledger wall", "两位阅读账目墙的访客"),
    role: T("Product and interaction design", "产品与交互设计"),
    collab: T("Product design project", "产品设计项目"),
    methods: [T("User research", "用户研究"), T("Information architecture", "信息架构"), T("Interface design", "界面设计")],
    results: [
      T("Market and user insight for bookkeeping mapped out", "梳理记账市场与用户洞察"),
      T("Key task flows completed", "完成关键任务流"),
      T("Product interface delivered", "交付产品界面方案"),
    ],
    hero: { ph: T("Huizhangbao product interface", "慧账宝记账产品界面"), ratio: "16 / 10",
            caption: T("A product concept for everyday bookkeeping", "面向日常记账的产品概念") },
    marks: [
      { x: 6.5, y: 38, w: 14, h: 23, c: "#bcd8b4" },
      { x: 27, y: 48, w: 6, h: 10, c: "#e6b053" },
      { x: 28, y: 48, w: 4, h: 5, c: "#c74a33" },
    ],
    sections: [
      S("background", LAB.background,
        T("Reducing the friction of bookkeeping", "降低记账摩擦"),
        T("Everyday bookkeeping has to balance the cost of entry, the value of looking back, and the motivation to keep going.",
          "日常记账需要在输入成本、回顾价值与持续动力之间取得平衡。"),
        T("The project looked for opportunities in the bookkeeping product market and in user research, focusing on how people record income and spending, understand that information, and come back to record again.",
          "项目从记账产品市场和用户调研中寻找机会，关注用户如何记录收支、理解信息并回到下一次记账。"),
        [{ src: "img/slides/huizhangbao/02.jpg", ratio: "3 / 2",
           caption: T("Research defines the product opportunity", "调研定义产品机会") }]),
      S("solution", LAB.solution,
        T("From insight to interface", "从洞察到界面"),
        T("The research results were turned into a clear core flow and a set of pages.",
          "研究结果被转化为结构清晰的核心流程和页面。"),
        T("I organised the research insights, built task flows for recording, reviewing and managing, and presented the path from action to review through information hierarchy and interface design.",
          "我整理研究洞察，构建记账、查看和管理等任务流，并以信息层级与界面方案呈现从操作到回顾的产品路径。"),
        [{ src: "img/slides/huizhangbao/04.jpg", ratio: "16 / 10",
           caption: T("Key flows and product interface", "关键流程与产品界面") }]),
      S("limits", LAB.limits,
        T("Next steps", "下一步"),
        T("A static design still has to be tested across a real bookkeeping cycle.",
          "静态方案仍需在真实记账周期中接受检验。"),
        T("Next it should be tested as an interactive prototype against different bookkeeping habits, watching whether users can complete entry quickly and understand the information, while handling the privacy and accuracy of financial information carefully.",
          "后续应以可交互原型测试不同记账习惯，观察用户是否能快速完成输入并理解信息，同时谨慎处理财务信息的隐私和准确性。")),
    ],
    figures: [
      { x: 6, y: 2.5, u: 3.1, coat: "#8fb0d2", legs: "#3b4a63", hair: "#2d2b2b", acc: "bag" },
      { x: 14, y: 1.5, u: 3.2, coat: "#e6d9b8", legs: "#2d2b2b", hair: "#2d2b2b" },
    ],
  },

  travelshu: {
    hall: "commercial", wall: "center", plate: "#dfe4ea", num: "05", theme: "#ff233f",
    year: "2024",
    kicker: T("Group chat · Travel AI agent", "小红书群聊 · 旅行 AI Agent"),
    title: T("Travel Shu", "旅游薯"),
    standfirst: T(
      "A product prototype that helps a group build an itinerary together, read a map and organise travel decisions inside a group chat.",
      "在小红书群聊场景中协助多人共建行程、查看地图并整理旅行决策的产品原型。"),
    audience: T("Three travellers comparing routes", "三位比较路线的旅客"),
    role: T("Map and route feature design, prototype collaboration", "地图与路线功能设计、原型协作"),
    collab: T("Team internet-product project", "团队互联网产品项目"),
    methods: [T("Product strategy", "产品策略"), T("Map experience", "地图体验"), T("AI product", "AI 产品")],
    results: [
      T("A running team prototype", "完成可运行的团队原型"),
      T("Map and route collaboration features defined", "定义地图与路线协作功能"),
      T("Feedback collected from 4 users", "收集 4 位用户的反馈"),
    ],
    hero: { src: "img/slides/travelshu/01.jpg", ratio: "16 / 10",
            caption: T("Collaborative itinerary planning inside a group chat", "群聊中的协作式行程规划") },
    marks: [
      { x: 40.5, y: 38, w: 10.5, h: 19, c: "#e6b053" },
      { x: 55, y: 41, w: 7, h: 11, c: "#c74a33" },
      { x: 56, y: 57, w: 3.5, h: 5, c: "#6d5090" },
    ],
    sections: [
      S("background", LAB.background,
        T("Turning a group chat into a workable itinerary", "把群聊变成可执行行程"),
        T("Travel decisions made by a group are usually scattered across messages, links and everyone's own preferences.",
          "多人旅行决策常散落在消息、链接和各自的偏好里。"),
        T("The project treats the group chat as an existing social and content setting, and explores how discussion, notes and route information can settle into one collaborative chain.",
          "项目以小红书群聊为既有社交与内容场景，探索如何让讨论、笔记和路线信息在同一条协作链路中沉淀。")),
      S("research", LAB.research,
        T("Requirements and the product's niche", "需求与生态位"),
        T("The team documentation and the technical route bound the product to travel planning inside a group chat.",
          "团队文档和技术路线把产品范围限定为群聊旅行规划。"),
        T("The requirements work connected group chat, note generation from links, map points and itinerary arrangement, so that users are not repeatedly copying information between tools.",
          "需求梳理将群聊、链接笔记生成、地图点位和路线安排连接起来，避免用户在多个工具之间反复复制信息。"),
        [{ src: "img/slides/travelshu/07.jpg", ratio: "3 / 2",
           caption: T("From group-chat content to travel decisions", "从群聊内容到旅行决策") }]),
      S("solution", LAB.solution,
        T("The map as a shared canvas", "地图作为共享画布"),
        T("The map and the route turn abstract discussion into spatial choices that can be compared.",
          "地图与路线让抽象讨论变为可比较的空间选择。"),
        T("I was responsible for the map and route design, focused on visualising places, order and itinerary suggestions, and on returning those results to the group chat for members to keep negotiating.",
          "我负责地图与路线相关设计，聚焦将地点、顺序和行程建议可视化，并让这些结果回到群聊中供成员继续协商。")),
      S("build", LAB.build,
        T("Landing the prototype", "原型落地"),
        T("The team turned the requirements into a workable group-chat, map and route flow.",
          "团队将需求转为可操作的群聊、地图和路线流程。"),
        T("The technical route covered basic group chat, note generation from links and the travel map; the team completed a prototype able to demonstrate the core flow, and I worked with them on implementing and validating the map and route experience.",
          "技术路线覆盖基础群聊、链接笔记生成和旅游地图；团队完成了能够演示核心流程的原型，我协同推进地图与路线体验的实现与验证。"),
        [{ src: "img/slides/travelshu/08.jpg", ratio: "16 / 10",
           caption: T("Schedule, and the existing group-AI entry the agent joins through", "排期，以及 Agent 借以加入的既有“群 AI”入口") }]),
      S("validation", LAB.validation,
        T("Early feedback", "早期反馈"),
        T("Feedback from four users was used to check whether the flow could be understood.",
          "四位用户的反馈用于检验流程是否可理解。"),
        T("4 users gave feedback after trying the prototype, which helped the team check the coherence from chat content to route suggestion, and exposed the prompts and collaboration states that still need to be made clearer.",
          "4 位用户体验原型后提供反馈，帮助团队检查从聊天内容到路线建议的连贯性，并暴露出需要继续明确的操作提示与协作状态。")),
      S("limits", LAB.limits,
        T("Next steps", "下一步"),
        T("The prototype proves the flow can be discussed; it still has to face the complexity of a real travel plan.",
          "原型证明流程可以被讨论，仍需面对真实旅行计划的复杂性。"),
        T("Further work should widen testing across different modes of travel and different groups, and examine the transparency of route suggestions, the handling of conflicting preferences, and reliability when third-party place data changes.",
          "后续应扩大不同出行方式与群体的测试，检验路线建议的透明度、冲突偏好的处理方式，以及第三方地点数据变化时的可靠性。")),
    ],
    figures: [
      { x: 39, y: 6, u: 1.9, coat: "#c74a33", legs: "#2d2b2b", hair: "#2d2b2b", sit: true },
      { x: 49, y: 2, u: 3.15, coat: "#efeee9", legs: "#5b7cb0", hair: "#2d2b2b", acc: "bag" },
      { x: 60, y: 6, u: 1.9, coat: "#8fb0d2", legs: "#e6d9b8", hair: "#8a5a3a", sit: true },
    ],
  },

  gdm: {
    hall: "commercial", wall: "right", plate: "#4e4276", num: "06", theme: "#1764f1",
    year: "2024",
    kicker: T("Design system · Large-model exploration", "设计系统 · 大模型探索"),
    title: T("Generative Design Model", "AI 生成式设计大模型"),
    standfirst: T(
      "An exploration of a design model that drives interface generation and validation from component definitions, annotation and structured specification.",
      "探索以组件定义、标注和结构化规范驱动界面生成与验证的设计模型。"),
    audience: T("Two designers reading the specification", "两位阅读规范的设计师"),
    role: T("Design research and prototype validation", "设计研究与原型验证"),
    collab: T("Design exploration project", "设计探索项目"),
    methods: [T("Design systems", "设计系统"), T("Prompts and specification", "提示与规范"), T("Prototype validation", "原型验证")],
    results: [
      T("Component and annotation inputs defined", "定义组件与标注输入"),
      T("SPEC and DSL expression built", "构建 SPEC 与 DSL 表达"),
      T("Rendering and QWEN validation trials completed", "完成渲染与 QWEN 验证试验"),
    ],
    hero: { ph: T("Generative design model concept", "生成式设计大模型概念展示"), ratio: "16 / 10",
            caption: T("An exploration of structured design generation", "结构化设计生成探索") },
    marks: [
      { x: 78, y: 38, w: 13, h: 22, c: "#e6b053" },
      { x: 74, y: 26, w: 4, h: 6, c: "#bcd8b4" },
      { x: 92.5, y: 47, w: 3.6, h: 6.5, c: "#c74a33" },
    ],
    sections: [
      S("background", LAB.background,
        T("Making design intent computable", "让设计意图可计算"),
        T("Generating an interface has to preserve component relationships and design judgement, not only copy a visual result.",
          "生成界面需要保留组件关系和设计判断，而不只是复制视觉结果。"),
        T("The project explores how component definitions, hierarchy and constraints can be organised into machine-readable input, so that generated results can be traced back to explicit rules in the design system.",
          "项目探索如何把组件定义、层级和约束整理成机器可读输入，使生成结果可以追溯到设计系统中的明确规则。")),
      S("build", LAB.build,
        T("SPEC, DSL and validation", "SPEC、DSL 与验证"),
        T("A structured specification links design annotation, model input and result checking.",
          "结构化规范连接设计标注、模型输入和结果检查。"),
        T("I annotated components and their properties, and described layout and relationships in SPEC and DSL; QWEN was then used for comprehension and generation trials, and the rendered results were checked against the source.",
          "我将组件及其属性进行标注，并以 SPEC 和 DSL 描述布局与关系；随后用 QWEN 进行理解与生成验证，再对渲染结果进行对照检查。"),
        [{ src: "img/slides/gdm/09.jpg", ratio: "3 / 2",
           caption: T("From component definition to structured input", "从组件定义到结构化输入") },
         { src: "img/slides/gdm/15.jpg", ratio: "3 / 2",
           caption: T("QWEN validation — the prompt, and the DSL generated from the SPEC", "QWEN 验证 — prompt 与由 SPEC 生成的 DSL") }]),
      S("limits", LAB.limits,
        T("Limitations", "局限"),
        T("A similar rendering does not mean the design judgement has been fully understood.",
          "渲染相似不等于设计判断已经被完整理解。"),
        T("The exploration is bounded by component coverage, annotation quality and the model's understanding of context; further work should test reusability against more complex interfaces, accessibility rules and human review.",
          "该探索受限于组件覆盖范围、标注质量和模型对上下文的理解；后续应以更多复杂界面、可访问性规则和人工评审来检验可复用性。")),
    ],
    figures: [
      { x: 80, y: 2, u: 3.15, coat: "#3b4a63", legs: "#e6d9b8", hair: "#2d2b2b" },
      { x: 88, y: 3, u: 3.0, coat: "#efeee9", legs: "#5c6046", hair: "#8a5a3a", acc: "bag" },
    ],
  },

  opencare: {
    hall: "early", wall: "left", plate: "#4e4276", num: "07",
    year: "2023",
    kicker: T("Health service · Rehabilitation training", "健康服务 · 康复训练"),
    title: T("OpenCare", "OpenCare"),
    standfirst: T(
      "A mobile service concept designed around the information, guidance and record-keeping needs of rehabilitation training after nasopharyngeal cancer.",
      "围绕鼻咽癌康复训练的信息、指导和记录需求设计的移动端服务概念。"),
    audience: T("A patient and a carer", "一位患者与一位陪护者"),
    role: T("User research and interaction design", "用户研究与交互设计"),
    collab: T("Health service design project", "健康服务设计项目"),
    methods: [T("Service design", "服务设计"), T("Information architecture", "信息架构"), T("Health experience", "健康体验")],
    results: [
      T("Information needs in rehabilitation settings mapped", "梳理康复场景中的信息需求"),
      T("A service information architecture built", "构建服务信息架构"),
      T("Training and record-keeping flows designed", "设计训练与记录流程"),
    ],
    hero: { src: "img/slides/opencare/01.jpg", ratio: "16 / 10",
            caption: T("A concept for rehabilitation information and training flow", "康复信息与训练流程概念") },
    marks: [
      { x: 7, y: 39, w: 14, h: 22, c: "#e6b053" },
      { x: 27, y: 50, w: 5.5, h: 9, c: "#bcd8b4" },
    ],
    sections: [
      S("background", LAB.background,
        T("Connecting rehabilitation information with daily training", "连接康复信息与日常训练"),
        T("Rehabilitation training needs clear information, executable steps and continuous records.",
          "康复训练需要清晰的信息、可执行的步骤和持续记录。"),
        T("OpenCare focuses on rehabilitation after nasopharyngeal cancer, and organises the breaks in information users may meet when understanding training content, arranging practice and reviewing progress.",
          "OpenCare 聚焦鼻咽癌康复情境，整理用户在理解训练内容、安排练习和回顾进展时可能遇到的信息断裂。"),
        [{ src: "img/slides/opencare/02.jpg", ratio: "3 / 2",
           caption: T("Background, patient and clinician interviews, and the needs drawn from them", "背景介绍、患者与医护访谈，以及由此得出的需求分析") }]),
      S("solution", LAB.solution,
        T("Service structure and flow", "服务结构与流程"),
        T("The information architecture organises guidance content, training tasks and the entry point for records together.",
          "信息架构把指导内容、训练任务和记录入口组织在一起。"),
        T("I turned the research results into a service architecture, and designed the interaction flow for training guidance and progress records, so a user can move from understanding what to do, into practice, and back to their own records.",
          "我将调研结果转为服务架构，并设计训练引导与进度记录的交互流程，使用户可以从了解事项进入练习，再回看自己的记录。"),
        [{ src: "img/slides/opencare/03.jpg", ratio: "3 / 2",
           caption: T("The service path of guidance, training and records", "指导、训练与记录的服务路径") },
         { src: "img/slides/opencare/04.jpg", ratio: "3 / 2",
           caption: T("AI guidance, chapter selection, guided training and data feedback", "AI 智能引导、康复章节选择、图线辅助训练与数据反馈") },
         { src: "img/slides/opencare/05.jpg", ratio: "3 / 2",
           caption: T("Outcome statistics, adherence assessment, community and training groups", "康复成效统计、依从性评估、互动社区与训练小组") }]),
      S("limits", LAB.limits,
        T("The boundary of a health service", "健康服务边界"),
        T("Product information and records cannot replace professional diagnosis or individual advice.",
          "产品信息与记录不能替代专业诊疗和个体化建议。"),
        T("Further work should validate content, accessibility and privacy arrangements together with clinical and rehabilitation professionals, and evaluate whether the flow suits real use at different stages of recovery.",
          "后续应与临床和康复专业人士共同验证内容、无障碍与隐私安排，并在不同恢复阶段的真实使用中评估流程是否合适。")),
    ],
    figures: [
      { x: 7, y: 2.5, u: 3.05, coat: "#efeee9", legs: "#3b4a63", hair: "#2d2b2b" },
      { x: 15, y: 1.5, u: 3.2, coat: "#9db39f", legs: "#e6d9b8", hair: "#d7d3d3" },
    ],
  },

  wanderland: {
    hall: "early", wall: "center", plate: "#dfe4ea", num: "08", fitWidth: true, theme: "#f79485",
    year: "2022",
    kicker: T("Interest community · Animal information", "兴趣社区 · 动物信息"),
    title: T("Wanderland", "Wanderland"),
    standfirst: T(
      "A mobile experience concept that brings animal information, interest conversation and community participation into one system.",
      "把动物信息浏览、兴趣交流和社区参与整合为一套移动端体验概念。"),
    audience: T("Two visitors seated, one reading", "两位坐着的访客与一位阅读者"),
    role: T("Information architecture and interface design", "信息架构与界面设计"),
    collab: T("Interaction design project", "交互设计项目"),
    methods: [T("Information architecture", "信息架构"), T("User flow", "用户流程"), T("Interface design", "界面设计")],
    results: [
      T("Animal information and community concept defined", "定义动物信息与社区概念"),
      T("User flows and information architecture built", "构建用户流程与信息架构"),
      T("Core application screens completed", "完成核心应用界面"),
    ],
    hero: { ph: T("Wanderland animal community app interface", "Wanderland 动物社区应用界面"), ratio: "16 / 10",
            caption: T("A concept for animal information and community experience", "动物信息与社区体验概念") },
    marks: [
      { x: 42, y: 38, w: 10, h: 18, c: "#bcd8b4" },
      { x: 56, y: 43, w: 6, h: 9, c: "#e6b053" },
    ],
    sections: [
      S("background", LAB.background,
        T("From browsing to taking part", "从浏览到参与"),
        T("Animal interest content needs both a trustworthy entry to information and a lightweight space to talk.",
          "动物兴趣内容既需要可信的信息入口，也需要轻量的交流空间。"),
        T("Wanderland explores how to organise animal information, paths of discovery and community interaction in one experience, so that users do not lose the thread between browsing content and taking part.",
          "Wanderland 探索如何在同一体验中组织动物信息、发现路径和社区互动，避免用户在内容浏览与参与之间失去线索。")),
      S("solution", LAB.solution,
        T("Structured exploration", "结构化探索"),
        T("Information architecture and user flow decide the order in which content is discovered and discussed.",
          "信息架构和用户流程决定了内容被发现和讨论的顺序。"),
        T("I designed the flow and page hierarchy from entering animal information, through content exploration, to community interaction, presenting the relationships between the entry points on the core screens.",
          "我设计了从动物信息进入、内容探索到社区互动的流程和页面层级，以核心屏幕呈现不同入口之间的关系。"),
        [{ src: "img/slides/wanderland/03.jpg", ratio: "16 / 10",
           caption: T("Paths of information discovery and community participation", "信息发现与社区参与路径") }]),
      S("limits", LAB.limits,
        T("Next steps", "下一步"),
        T("A community concept has to be validated against real content quality and real participation behaviour.",
          "社区概念需要在真实内容质量和参与行为中验证。"),
        T("Further work should test how users understand categories, recommendations and the posting entry point, and set rules for content sources, moderation and privacy, so community interaction does not come at the cost of reliable information.",
          "后续应测试用户对分类、推荐和发帖入口的理解，并制定内容来源、审核和隐私规则，确保社区互动不会牺牲信息可靠性。")),
    ],
    figures: [
      { x: 43, y: 6, u: 1.9, coat: "#8a6b4a", legs: "#2d2b2b", hair: "#2d2b2b", sit: true },
      { x: 52, y: 2, u: 3.1, coat: "#e6d9b8", legs: "#3b4a63", hair: "#2d2b2b" },
      { x: 60, y: 6, u: 1.9, coat: "#bcd8b4", legs: "#8fb0d2", hair: "#8a5a3a", sit: true },
    ],
  },

  philips: {
    hall: "early", wall: "right", plate: "#26406d", num: "09", fitWidth: true, theme: "#3a3c66",
    year: "2023",
    kicker: T("UI/UX internship · Smart shaving", "UI/UX 实习 · 智能剃须"),
    title: T("Smart Shaver UI/UX Internship", "剃须刀 UI/UX 实习"),
    standfirst: T(
      "Work on UI proposals, mode expression and testing learnings for a smart shaving experience during an internship.",
      "在实习项目中参与智能剃须体验的 UI 方案、模式表达与测试学习。"),
      audience: T("Two visitors at the interface wall", "界面墙前的两位访客"),
    role: T("UI/UX design intern", "UI/UX 设计实习生"),
    collab: T("Collaboration with a shaver experience team", "与剃须刀体验团队协作"),
    methods: [T("UI design", "UI 设计"), T("Interaction expression", "交互表达"), T("Usability testing", "可用性测试")],
    results: [
      T("Contributed to the UI expression of five smart shaving modes", "参与五种智能剃须模式的 UI 表达"),
      T("Iterated several sets of interface proposals", "迭代多组界面方案"),
      T("Learned experience details through testing", "通过测试学习体验细节"),
    ],
    hero: { ph: T("Watermarked smart shaving interface — public derivative media only", "已加水印的智能剃须体验界面 — 仅公开衍生素材"), ratio: "16 / 10",
            caption: T("Public presentation uses watermarked derivative material only", "公开展示仅使用水印衍生素材") },
    marks: [
      { x: 79, y: 38, w: 12, h: 21, c: "#dcd8d0" },
      { x: 92.5, y: 48, w: 3.4, h: 6, c: "#e6b053" },
    ],
    sections: [
      S("background", LAB.background,
        T("Expressing smart modes clearly", "清晰表达智能模式"),
        T("The internship work focused on turning different shaving modes into an interface experience that can be understood and operated.",
          "实习工作聚焦将不同剃须模式转化为可理解、可操作的界面体验。"),
        T("Under the team's guidance I took part in the UI/UX design of the smart shaving experience, refining the interface expression around the states, information hierarchy and operational feedback of five modes.",
          "我在团队指导下参与智能剃须体验的 UI/UX 设计，围绕五种模式的状态、信息层级和操作反馈完善界面表达。")),
      S("solution", LAB.solution,
        T("Interface proposals and testing", "界面方案与测试"),
        T("Several sets of proposals were used to discuss how the modes are distinguished and how they are used.",
          "多组方案用于讨论模式之间的区分和使用流程。"),
        T("I took part in making and comparing different UI proposals, and organised learnings on interface comprehension, information prompts and interaction pace from test observation; the public content contains no internal data or unpublished process.",
          "我参与制作和比较不同 UI 方案，并结合测试观察整理界面理解、信息提示和交互节奏上的学习；公开内容不包含内部数据或未公开流程。"),
        [{ src: "img/slides/philips/02.jpg", ratio: "16 / 10",
           caption: T("Iteration on mode expression", "模式表达的界面迭代") }]),
      S("limits", LAB.limits,
        T("What the internship gave, and its boundary", "实习收获与边界"),
        T("The public case emphasises personal method and learning; it does not disclose business-sensitive content.",
          "公开案例强调个人方法与学习，不披露业务敏感内容。"),
        T("The experience let me practise expressing design judgement inside an existing product framework and cross-functional collaboration; this case keeps only watermarked public derivative media, and omits internal metrics, user profiles and commercial detail.",
          "这段经历让我练习在既有产品框架和跨职能协作中表达设计判断；本案例仅保留经过水印处理的公开衍生媒体，并省略内部指标、用户资料与商业细节。")),
    ],
    figures: [
      { x: 80, y: 2, u: 3.1, coat: "#5b7cb0", legs: "#e6d9b8", hair: "#2d2b2b" },
      { x: 88, y: 3, u: 3.0, coat: "#dcd8d0", legs: "#2d2b2b", hair: "#2d2b2b", acc: "bag" },
    ],
  },
};

// Parts derived from each project's own source document: the section titles are the
// document's headings (Chinese verbatim), with an English translation for the EN view.
// slides[] are page images rendered from those same sources.
const S2 = (id, label, summary, slides, code, video) => ({ id, label, summary, slides: slides || [], code: code || null, video: video || null });
const sl = (proj, ns) => ns.map(n => "img/slides/" + proj + "/" + String(n).padStart(2, "0") + ".jpg");

const PARTS = {
  talevision: {
    source: T("Graduation defence deck, 23 slides", "毕业设计答辩 PPT，23 页"),
    parts: [
      S2("bg", T("Design background", "一 设计背景"),
        T("China has 17.3 million people with visual impairment, and children make up 23% of them. Most retain some light perception, but moderate-to-severe loss challenges their development across perception, attention, memory, thinking and language. Chinese braille is phonetic, so the link between a word's sound, its shape and its meaning is hard to build, and teaching aids for this are largely missing from the market.",
          "我国视障者总数已达 1730 万人，视障儿童占其中 23%。大部分仍保有光感，但中度至盲的视力损伤使他们在感觉、知觉、注意、记忆、思维、语言等维度的认知发展遭受重大挑战。汉语盲文是拼音文字，音、形、义之间的联系难以建立，而针对这一问题的教具仍存在市场空白。"),
        sl("talevision", [1,2,3,4,5,6,7])),
      S2("research", T("User research", "二 设计调研"),
        T("Existing aids for children with visual impairment are low in intelligence and narrow in the senses they engage — blocks, cards and touch pads. Fieldwork at Shanghai School for the Blind found every aid was hand-made by teachers. Two personas came out of it: Xiaozhi, six, congenitally blind and in his first year of braille; and Yayuan, 28, a young braille teacher learning the language from scratch alongside her pupils.",
          "现有针对视障儿童的设计智能化程度低，以积木、卡片、触摸板为主要形态，涉及感官较为单一。上海市盲童学校的调研发现，目前所有教具都是老师手工制作。由此形成两个人物模型：六岁的先天全盲儿童小智，正在一年级学习盲文；以及 28 岁的盲校盲文老师雅媛，需要和孩子们一样从头学习这门语言。"),
        sl("talevision", [8,9,10,11])),
      S2("scheme", T("Design scheme", "三 设计方案"),
        T("The interaction chain joins AI generation to multisensory perception: the child reads braille aloud, the system generates an image and sound, and the image is converted into tactile dots. Electromagnetic drive was chosen for the tactile display after weighing size, portability, response speed, dot support force and cost, and verified with a multi-channel relay array.",
          "交互流程将 AI 生成与多模态感知连接起来：儿童朗读盲文，系统生成图像与声音，图像再转换为触觉颗粒。触觉显示装置综合考虑装置尺寸、便携程度、响应速度、触点支撑力及成本后选择电磁式驱动，并以多路继电器基本验证实现控制。"),
        ["img/slides/talevision/12.jpg",
         "img/slides/talevision/d1.jpg", "img/slides/talevision/d2.jpg", "img/slides/talevision/d3.jpg",
         "img/slides/talevision/d4.jpg", "img/slides/talevision/d5.jpg", "img/slides/talevision/d6.jpg",
         "img/slides/talevision/d7.jpg",
         "img/slides/talevision/15.jpg"],
        null, { src: "video/talevision.mp4", poster: "video/talevision-poster.jpg", caption: T("Graduation project film — the device turning speech into a tactile image", "毕业设计视频 — 从语音到触觉图像的完整演示") }),
      S2("test", T("Prototype test", "四 原型测试"),
        T("The software runs in Python: Baidu speech recognition turns voice into text, DALL·E 3 generates the image, and OpenCV pixelates, binarises and resizes it to match the Unity front-end block array. Two sighted testers identified a dog pattern in 90 and 120 seconds and asked for rounded dot edges. Three older blind participants tested the prototype — one noted how hard same-sound different-meaning words are to tell apart, another asked for three-dimensional relief, a third wanted it for museum objects he could neither see nor touch.",
          "软件采用 Python 开发，利用百度语音识别 API 将语音转换为文本，调用 DALL·E 3 生成图像，图像再经 OpenCV 像素化、二值化和尺寸调整，以匹配 Unity 前端的方块阵列。两位明眼测试者分别用 90 秒和 120 秒猜出小狗图案，并建议为颗粒增加圆角。三位老年盲人参与原型测试：一位提到同音不同意的字词很难分辨，一位希望有立体的浮雕效果，另一位希望能用于自己看不到也摸不着的博物馆文物。"),
        sl("talevision", [16,17,18,19,20])),
      S2("outlook", T("Summary & outlook", "五 总结展望"),
        T("Four directions remain: simulating depth from pixel value for 3D relief, personalised learning plans from usage data, a game mechanic for braille learning, and a connected TaleVision world where sighted children join as storytellers. As the closing slide puts it, fairness is the enduring pursuit of education, and how new technology reaches disadvantaged groups rather than widening the gap is a question for the whole society.",
          "未来可从四个方面继续完善：根据图像像素深浅模拟深度实现 3D 立体效果；收集使用数据形成个性化学习方案；以游戏化方式构建盲文学习架构；以及构建 TaleVision 互联世界，让明眼儿童加入担任讲故事画故事的角色。正如结语所说，公平是教育世界的永恒追求，如何避免弱势群体与整个社会的差距加深，是我们整个社会应当不断反思探索的领域。"),
        sl("talevision", [21,22,23]),
        null, { src: "video/talevision-defence-school.mp4", poster: "video/talevision-defence-school-poster.jpg", caption: T("School defence presentation, recorded in full", "学院答辩视频全程记录") }),
    ],
  },

  mirrorcle: {
    source: T("Project boards, 5 panels", "项目展板，5 张"),
    parts: [
      S2("bg", T("Background & research", "Background & Research"),
        T("Autism spectrum disorder affects about one child in 36. Desk research was followed by primary research — online interviews with autism experts and parents — to understand where expression recognition and imitation break down in daily life.",
          "自闭症谱系障碍（ASD）的发生率约为 1/36。团队在文献研究之后开展了一手调研，通过线上访谈自闭症专家与家长，理解表情识别与模仿在日常生活中受阻的环节。"),
        sl("mirrorcle", [1,2])),
      S2("persona", T("Persona, brainstorm & prototype", "Persona, Brainstorm & Prototype"),
        T("Insights became a persona, then a brainstorm, a first round of testing, a paper prototype and a hardware choice — the sequence that settled what the product would physically be.",
          "洞察转化为人物模型，再经过头脑风暴、第一轮测试、纸原型与硬件选型，逐步确定产品的实体形态。"),
        sl("mirrorcle", [3])),
      S2("highfi", T("High-fidelity design & story board", "High-fi & Story Board"),
        T("The high-fidelity design pairs an interactive picture book with a live animated mirror, laid out as a story board across locating, playing and pondering with Mirrorcle, with the technical support each step needs.",
          "高保真设计将互动绘本与实时动画镜像结合，以故事板呈现使用 Mirrorcle 时的定位、游玩与思考流程，并标注每一步所需的技术支持。"),
        sl("mirrorcle", [4]),
        null, { src: "video/mirrorcle.mp4", poster: "video/mirrorcle-poster.jpg", caption: T("Mirrorcle walkthrough — picture book, expression practice and mirror feedback", "镜遇演示 — 互动绘本、表情练习与镜像反馈") }),
      S2("testing", T("Secondary testing & future", "Secondary Testing & Future"),
        T("Secondary testing compared a teacher-led group with a Mirrorcle group in active learning, then mapped where the product sits after use and where it could focus next, including its business map.",
          "第二轮测试将教师组与 Mirrorcle 主动学习组进行对照，并梳理产品在使用之后的位置与未来的着力方向，包括商业模式图。"),
        sl("mirrorcle", [5])),
    ],
  },

  huizhangbao: {
    source: T("Project boards, 4 panels · course project with Ant Group", "项目展板，4 张 · 设计调研课程 × 蚂蚁集团"),
    parts: [
      S2("overview", T("Overview", "项目概览"),
        T("Huizhangbao is smart financial management software aimed at university students, made for a design research course in collaboration with Ant Group.",
          "慧帐宝是一款面向大学生的智慧财务管理软件，为设计调研课程与蚂蚁集团合作完成。"),
        sl("huizhangbao", [1])),
      S2("market", T("Market & user research", "记账软件市场概况 · 用户研究"),
        T("The work began with a survey of the bookkeeping software market, then qualitative interviews and a quantitative questionnaire to understand how students actually record and review spending.",
          "工作从记账软件市场概况入手，再通过定性访谈与定量问卷，理解大学生实际记录与回顾收支的方式。"),
        sl("huizhangbao", [2])),
      S2("quant", T("From research to design", "设计调研 → 设计"),
        T("Quantitative questionnaire findings were turned into design decisions, tracing each research conclusion through to the feature it justifies.",
          "问卷定量研究的结论被转化为设计决策，将每一条研究发现对应到它所支持的功能。"),
        sl("huizhangbao", [3])),
      S2("interface", T("Product interface", "产品界面"),
        T("The final interface covers the spending scenarios the research identified, from painless saving to the pressure of paying friends back.",
          "最终界面覆盖调研识别出的消费场景，从无痛省钱到人情往来的还款压力。"),
        sl("huizhangbao", [4])),
    ],
  },

  travelshu: {
    source: T("Full team project document, 16 pages", "【项目完整文档】小红书群聊旅游 AI，16 页"),
    parts: [
      S2("status", T("Current situation — user needs", "一、现状——用户需求"),
        T("Three pain points open the document: coordinating an itinerary online before a group trip is difficult, sharing travel guides across platforms is a nuisance, and planning a route costs real time and effort.",
          "文档以三个痛点开篇：多人出游前线上沟通行程协同困难、跨平台分享旅游攻略麻烦、制定路线耗时耗力。"),
        sl("travelshu", [2])),
      S2("competitor", T("Competitor analysis", "二、竞品分析"),
        T("Travel AI products each address the upstream (searching for information), midstream (route customisation) or downstream (hotels, flights, sights, food). Content platforms lead upstream, startups like 圆周旅迹 currently win on route customisation, and local-life platforms connect best downstream — though users still cross platforms to compare prices before buying. The conclusion: enter where you are already strong, then absorb the rest, with deep integration into your own content ecosystem and moving away from the chatbot form as the key levers.",
          "各旅游 AI 产品分别着眼上游（旅游信息搜寻）、中游（路线定制）或下游（酒店/机票/景点/美食）。内容大厂以攻略生态见长，圆周旅迹等初创公司在路线定制上暂时胜出，本地生活平台更好衔接下游——但用户在最终消费前仍会跨平台比价。结论是：各家先从自己擅长的环节切入，再兼并其他上中下游，而“与本身产品/内容生态深入结合”“去 chatbot 化”是关键发力点。"),
        sl("travelshu", [3])),
      S2("advantage", T("Why a travel group-chat AI belongs in this app", "三、小红书中做旅游群聊 AI 的优势"),
        T("Two structural advantages: the platform's travel and guide content ecosystem is unusually rich — it started with overseas travel guides — and its image-plus-video format carries more than text-led or video-only competitors.",
          "两项结构性优势：本身旅游/攻略内容的生态十分丰富（最早就是做海外旅游攻略起家），且图文加视频的内容形式比偏纯文字或偏纯视频的平台更有优势。"),
        []),
      S2("product", T("Product introduction", "四、产品简介"),
        T("The agent covers three stages of a trip. Upstream, it reads the group's needs and preferences and summarises a personalised guide from the platform's travel content. Midstream, it generates an editable itinerary from the chat history, where every place links back to the note that recommended it, and any member can edit. Downstream — hotel recommendation and booking — was scoped out of this build. The value is a shorter path for the user and growth in social ties, content consumption and travel business for the platform.",
          "该 Agent 覆盖旅游的三个阶段。上游：综合群成员的需求与偏好，依托平台丰富的旅游内容自动总结出个性化攻略。中游：根据群聊聊天记录生成可编辑的行程列表，每个地点均可关联到对应的推荐笔记，群聊中每个成员都可以编辑。下游的酒店推荐与预定暂时未做。其价值在于优化用户操作链路，并赋能平台的社交关系、内容消费与酒旅业务增长。"),
        sl("travelshu", [1,4,5])),
      S2("requirements", T("Requirements list", "五、需求清单"),
        T("Seven P0/P1 requirements with owners and status, from building the AI workflow on coze and packaging it as an API, through the group-chat message handler and chat interface, to search and recommendation. Items 5 and 6 were mine: visualising the coordinates of each place on the map, and the route list UI that strings the places into a line.",
          "七项 P0/P1 需求，标注负责人与进度：从在 coze 上搭建 AI 工作流并打包为 API，到模拟群聊的信息处理器、群聊基础界面，再到检索与推荐工具开发。其中第 5、6 项由我负责：旅游景点坐标点在地图上的可视化，以及旅游路线列表 UI 与各景点串联成线。"),
        sl("travelshu", [7])),
      S2("prototype", T("Prototype & technical implementation", "六、原型&技术实现方式"),
        T("The AI joins through the platform's existing group-AI entry point. Place names are pulled from the guide text by named entity recognition, with text classification, relation extraction and keyword extraction; those names go through POI search and geocoding to become coordinates, then the route planning API strings them in order and draws the line on the map. The itinerary list supports drag-to-reorder, kept in sync with the map markers.",
          "AI 通过平台已有的“群 AI”入口加入，直观简便。景点信息由命名实体识别从攻略文本中提取，辅以文本分类、关系抽取与关键词提取；地点名称经 POI 搜索与地理编码 API 转换为经纬度，再由路径规划 API 按顺序串联并在地图上绘制路线。行程列表支持拖拽排序，并与地图标记保持同步。"),
        sl("travelshu", [6,8,9]),
        { lang: "Swift", label: T("Map view model — parsing the cached itinerary", "地图视图模型 — 解析缓存的行程 JSON"),
          text: "class MapViewModel: ObservableObject {\n    @Published var city: String = \"\"\n    @Published var sites: [Site] = []\n    @Published var groupedSites: [String: [Site]] = [:]\n    @Published var dayKeys: [String] = []\n\n    func loadSites() {\n        guard let url = URL(string: \"http://localhost:3000/api/site-data\")\n        else { return }\n        var request = URLRequest(url: url)\n        // deserialise the response, then group the sites by day\n        // so the view layer can present the trip day by day\n    }\n}" },
        { src: "video/travelai.mp4", poster: "video/travelai-poster.jpg",
          caption: T("Prototype demonstration — group chat, generated itinerary and the map", "原型演示 — 群聊、生成行程与地图") }),
      S2("feedback", T("User trial feedback", "七、用户试用反馈"),
        T("Four users tried the prototype. They valued planning inside a platform they already use daily with nothing extra to install, having map and itinerary in one place, and coverage of destinations outside China that other planners lacked; one non-planner liked that a chat-shaped itinerary felt less daunting than a friend's spreadsheet. The gaps were consistent: let me edit the generated route and adjust time per sight, add food and lodging recommendations, constrain distance so routes stay sensible, break up the wall of summary text, allow specific messages to be selected when the chat contains noise, and give the map a whole-trip overview.",
          "四位用户试用了原型。他们认可在日常已经使用的平台内完成规划、无需额外安装；地图路线与规划信息整合在一起，不必跳转多个软件；以及国内外旅游信息都能查询，覆盖范围比其他规划软件更广；一位平时不参与规划的用户则表示，聊天形式的行程不像朋友做的复杂 Excel 表那样有压力。不足也很一致：希望能编辑生成的路线并调整每个景点的时长、补充餐饮住宿推荐、对里程与数量加以限定避免不合理的超远线路、拆分大段纯文字的总结、在群聊信息嘈杂时可选择特定聊天记录，以及在地图中增加整趟行程的路线总览。"),
        []),
      S2("tutor", T("Tutor feedback", "八、老师反馈"),
        T("Two notes: the guide should be able to output a long image and other shareable forms, and a small mock field collecting destination, days and dates would filter the noise out of a busy group chat.",
          "两点意见：攻略内容可以输出长图或更多分享形式；群聊消息很多时，可以用一个小的 mock 栏采集用户的目的地/天数/时间需求，以规避无效消息。"),
        []),
    ],
  },

  hermoony: {
    source: T("Mid-term graduation review deck, 25 slides", "毕设中期汇报，25 页"),
    parts: [
      S2("bg", T("Research background", "研究背景"),
        T("According to WHO data and epidemiological studies, roughly 45% to 95% of women of reproductive age experience dysmenorrhoea to some degree, and among adolescents the rate reaches as high as 93%. Beyond lower abdominal pain it commonly brings headache, nausea, diarrhoea and fatigue, and it measurably affects study, work efficiency, social participation and mental health. PMS adds a cyclical layer of anxiety, irritability, mood swings and reduced concentration in the luteal phase.",
          "据世界卫生组织及多项流行病学研究的数据，约 45% 至 95% 的育龄女性在不同程度上经历过痛经，而在青少年群体中其发生率甚至可高达 93%。除了下腹部疼痛，患者常伴随头痛、恶心、腹泻、疲劳等一系列躯体症状，也会对学习、工作效率、社会参与以及心理健康产生显著影响。PMS 则在月经来潮前的黄体期出现周期性的焦虑、易怒、情绪波动、疲劳以及注意力下降。"),
        sl("hermoony", [1,2,3])),
      S2("why", T("Why VR", "为什么使用 VR"),
        T("Painkillers carry side effects and long-term use can bring gastrointestinal problems, so many women would rather not take them frequently; existing non-drug methods — heat, yoga, meditation — depend on the user's sustained self-control and concentration. VR analgesia is already evidenced in burn dressing changes, post-operative pain, chronic pain and dental treatment, and by cognitive distraction and gate control theory its multisensory peripherals relieve pain through subjective cognition and neural inhibition. Since dysmenorrhoea is not only physical pain but comes with anxiety, mood swings and stress, immersion also suits relaxation training, meditation and emotional regulation. The research contributes two innovations: a multisensory immersive pain-intervention perspective that starts from women's own experience, and a generative companion interaction mechanism based on breath sensing.",
          "止痛药有副作用，长期使用可能带来胃肠问题，不少女性不希望频繁服用；现有非药物方法（热敷、瑜伽、冥想）依赖用户的持续自我控制和专注。VR 在疼痛管理中已被证明有效（烧伤换药疼痛、术后疼痛、慢性疼痛、牙科治疗疼痛），根据认知分心理论、门控理论等，VR 及其多感官外设的镇痛机制在主观认知、神经抑制下可以缓解疼痛。痛经不仅是生理性疼痛，同时伴有焦虑、情绪波动、压力，而 VR 的沉浸式体验正适合放松训练、冥想、情绪调节。本研究的创新在于：从女性经验出发的多感官沉浸式疼痛干预视角，以及基于呼吸感知的生成式陪伴交互机制。"),
        sl("hermoony", [4,5])),
      S2("interview", T("Design research — interviews", "设计调研 · 访谈"),
        T("Three in-depth interviews of 2.5 hours each produced an empathy map and three personas. Freda.Z, 24, a lawyer, rates her pain 7–9 and pushes through work anyway — a high-pressure endurer who needs low-stimulus, low-cognitive-load quiet. QiuQiu.Lin, 25, a game designer, rates it 9–10, swings between elation, collapse and anxiety, and plays games to move her attention elsewhere — a low-energy escaper who needs immersive distraction. Regina.Y, 23, an intern, rates it 7–8 with cold sweats, weakness and nausea, and worries beforehand that her plans will be disrupted.",
          "三场每场 2.5 小时的深度访谈形成了同理心地图与三个人物画像。24 岁律师 Freda.Z 每次痛经疼痛程度 7–9 分，工作中仍需强撑，属于高压强撑型，需要低刺激、低认知负荷的安静空间。25 岁游戏设计师 QiuQiu.Lin 疼痛程度 9–10 分，情绪大起大落，亢奋 ↔ 崩溃 ↔ 焦虑，会通过打游戏转移注意力，属于低能量逃离型，需要沉浸式转移。23 岁互联网实习生 Regina.Y 疼痛 7–8 分，伴随冷汗、发冷、乏力、恶心，经前焦虑，担心计划被打乱。"),
        sl("hermoony", [6,7,8,9])),
      S2("affinity", T("Affinity map & survey", "亲和图与问卷分析"),
        T("The affinity map turned the character of the pain into design implications: it recurs monthly, is predictable yet still uncertain, differs greatly between individuals, and is quickly forgotten once over — so the system needs whole-cycle company rather than one-off intervention, a pre-menstrual reminder and preparation mode, symptom triage rather than breathing alone, emotion recognition split into soothing and venting modes, and a record of what worked to inform next time. Of 52 questionnaire responses, 67.3% experience pain every or most cycles; 36.5% report moderate and 36.5% severe pain; irritability reaches 76.9% and tearfulness 53.9%. On sensory preference: natural scenes 71.2%, warm tones with slight movement 63.5%, natural sound 80.8%, and abdominal warmth 86.5%.",
          "亲和图把痛经特性转化为设计启发：周期性每月反复、可预测但仍有不确定性、个体差异较大、疼痛结束后容易遗忘——因此需要全周期陪伴而不是一次性干预，需要经前提醒与预备模式，需要症状分流而不是单一呼吸，需要情绪识别并分安抚/发泄模式，并记录有效方法为下次推荐。52 份问卷中，每次+大部分占比 67.3%，中度疼痛 36.5%、重度疼痛 36.5%；伴随情绪以烦躁易怒 76.9%、低落想哭 53.9% 为主。感官偏好方面：自然类场景 71.2%、暖色调与轻微动态变化 63.5%、自然声 80.8%、腹部温热 86.5%。"),
        sl("hermoony", [10,11,12])),
      S2("journey", T("Pain journey map", "经期疼痛旅程图"),
        T("The journey map traces psychological and physical lines together across the cycle: mood swings and body signals before onset, the relief of finally starting, pain arriving as cramping, nausea and cold sweats, attention gradually taken over by it, the intertwined distress of pain that keeps returning, then the fall as medication takes effect, recovery — and how quickly the whole experience is forgotten.",
          "旅程图将心理与生理两条线并置：经前的情绪波动与身体信号，终于来潮的释怀，痛感来袭时的腹部绞痛、恶心腹泻与冷汗发冷，注意力逐渐被痛感占据，因为痛感时不时来袭而感到的郁闷痛苦，随着药效起效痛感慢慢减弱，身体修复，以及快速遗忘痛经感受。"),
        sl("hermoony", [13])),
      S2("system", T("System design", "系统设计"),
        T("HerMoony is an AI companion multisensory system: an immersive VR healing environment for sight and sound, a soft physical silicone lamp for light and touch, a warming abdominal massage belt for heat, and an AI companion system reading the user's state. The interaction system runs across three stages. Before menstruation the agent asks about emotional state, explains hormonal fluctuation and body change, and prompts preparation of medication, heat source and sanitary products, while VR opens the month's journey as a walk into an unknown forest where plants along the path reveal hormone diagrams. During pain the agent assesses symptoms and controls the healing mode, and VR seals off the real environment with nature, home or release scenes, breath rhythm and the warm belt. Afterwards it records the pain, emotion, symptoms and what helped, generates a monthly journey report, and gives moon badges and a cycle garden.",
          "HerMoony 是 AI 陪伴式多感统系统：视听为 VR 沉浸式疗愈环境，光触为实体柔软硅胶灯，热感为腹部热敷按摩带，并由 AI 陪伴系统读取用户状态反馈。交互系统分三个阶段。经前 PMS 期，Agent 主动询问情绪状态、解释激素波动与身体变化、提醒准备药物、热源与卫生用品，VR 场景则以慢慢步入一片未知森林开启本月经期旅程，小径两旁的植物可点击查看激素可视化图解。经期疼痛中，Agent 进行症状评估、引导用户使用 VR、推荐并控制疗愈模式，VR 沉浸隔绝现实环境，提供自然/居家/释压场景加呼吸节律与温热腹部按摩带。经后恢复期，记录本次疼痛/情绪/症状/缓解方式，生成本月旅程报告，并给予月亮徽章与周期花园等成就鼓励。"),
        sl("hermoony", [14,15,16,17,18])),
      S2("agent", T("Agent app & VR scene generation", "Agent App 与 VR 场景生成"),
        T("The agent app carries the conversation and the home screen. For scene generation the work compared World Labs' Marble, Blockade Labs' Skybox AI — a model dedicated to 360-degree skybox backgrounds whose output is low fidelity and cannot form a complete 3D USD scene, only exported mesh faces — and Meshy AI for real 3D foreground objects. The next iteration will call both APIs behind prompt templates so users can generate their own preferred healing world.",
          "Agent App 承载智能对话与主页。VR 场景生成方面比较了 World Labs 的 Marble 模型、Blockade Labs 的 Skybox AI 模型（用于生成 360 度天空盒背景的专用模型，生成的场景保真度低，且无法形成一个完整的 3D USD 场景，只是把生成的 Mesh 面导出），以及用于生成前景真实 3D 物体模型的 Meshy AI。后续迭代将调用两者的 API 接口，提供 prompt 模版，让用户自行生成自己偏好的疗愈世界。"),
        sl("hermoony", [19,20,21])),
      S2("plan", T("Research plan", "研究计划"),
        T("A longitudinal user experiment evaluates the system's effect on subjective and objective pain relief, emotional relaxation, body awareness, sense of pain control and self-management. RQ1 asks whether the multisensory VR healing lowers pain, emotional load and physical tension during menstruation; RQ2 whether whole-cycle agent company improves understanding of one's own body state, sense of control and self-management. Three hypotheses follow, measured against CBT and cognitive distraction / gate control theory with VAS pain scores, PSEQ, PCS and MAIA adapted questionnaires and physiological signals — HR/HRV, EDA and respiration. The protocol runs a baseline cycle without the system to build a personal cycle profile, then an agent-plus-VR intervention cycle across pre-menstrual understanding, mid-cycle healing on Apple Vision Pro with breath guidance and warm rhythmic feedback, and post-menstrual data review, stratified by baseline NRS: mild 2–3, moderate 4–6, severe 7–8.",
          "本研究通过纵向用户实验评估全周期 Agent 陪伴与 VR 多感官疗愈系统在女性经期疼痛管理中的应用效果，重点考察对主客观疼痛缓解、情绪放松、身体觉察、疼痛掌控感和自我管理能力的影响。RQ1 关注即时疗愈效果：VR 多感官疗愈是否能在痛经中降低主客观疼痛、情绪负荷和身体紧张；RQ2 关注全周期陪伴体验是否能提升用户对经期身体状态的理解、疼痛掌控感与自我管理能力。研究以认知行为疗法（CBT）和认知分心理论/门控理论为支撑，测试指标包括 VAS 疼痛评分、PSEQ 经期疼痛自我效能适配问卷、PCS 经期疼痛灾难化适配问卷、MAIA 经期身体觉察适配问卷，以及 HR/HRV、EDA、呼吸等生理信号。实验流程先以基线周期不使用系统建立个人周期画像，再进入 Agent+VR 干预周期：经前理解、经中在 Apple Vision Pro 上配合呼吸引导与温热律动反馈疗愈、经后数据复盘，并按基线 NRS 分层：轻度 2–3、中度 4–6、重度 7–8。"),
        sl("hermoony", [22,23,24,25])),
    ],
  },

  gdm: {
    source: T("Design model report, 20 slides", "生成式设计大模型工作总结，20 页"),
    parts: [
      S2("groundwork", T("Groundwork: definition & annotation", "01 前期基础工作"),
        T("Elements are the basis of a page and compose components and containers, so each was defined by its own properties — text by font, alignment, fill, height and sizing; icons by data and fill; images by size, fill and data; shapes by fill, size, border and corner radius. Container components were defined the same way: dropdown, side navigation, radio, checkbox, button, tree, menu, form, breadcrumb and tabs, each with properties, layout and interaction states.",
          "元件是页面基础，组成了组件和容器组件，因此按各自特点逐一定义：TEXT 定义 FONT、ALIGN、FILL、HEIGHT、SIZING；ICON 定义 DATA、FILL；IMG 定义 SIZE、FILL、DATA；SHAPE 定义 FILL、SIZE、BORDER、CORNER RADIUS。容器组件同样按特点定义：下拉菜单、侧边导航栏、单选、复选框、按钮、结构树、菜单、表单、面包屑、页签，并标注属性、布局与交互状态。"),
        sl("gdm", [1,2,3,4,5,6])),
      S2("spec", T("SPEC & DSL determination", "02 SPEC & DSL 确定"),
        T("SPEC describes a page as JSON — a navigation area and a body, each listing its components with a custom function description drawn from a fixed set: display, input, select, edit, trigger. The DSL builds a view tree from annotated wireframe data: starting at the page root, child nodes are those whose bounding box is contained by no other, added in reading order and recursed to the leaves, with every node carrying type, content, child and bbox. QWEN was then prompted to produce SPEC from a designer's description and DSL from that SPEC, and the DSL was rendered in the front end to compare against the original page.",
          "SPEC 以 JSON 描述页面：一个导航区与一个 Body，各自列出所含组件，并从展示、输入、选择、编辑、触发（跳转）中选择自定义功能描述。DSL 基于标注线框数据构建“视图树”：从根节点 PAGE 开始，选出 BBOX 不被任何其余节点包含的 CHILD 节点，按从上到下、从左到右的阅读顺序加入树中并递归至叶子节点，每个节点包含 TYPE、CONTENT、CHILD、BBOX 四个 KEY。随后以 QWEN 验证：由设计师描述生成 SPEC，再由 SPEC 生成完整 DSL，并在前端渲染 DSL 与原网页对照。"),
        sl("gdm", [7,8,9,10,11,12,13,14,15])),
      S2("flywheel", T("Data flywheel", "03 数据飞轮"),
        T("The flywheel turns users of the design-model plugin into data, and data into a better model. Directly extracted signals include product views, uses, repeat input rate, output selection rate and time, and output modification rate and steps; indirect ones include favourites, likes, dislikes, comments and A/B tests. The data has to be cheap, plentiful and genuinely able to improve efficiency and precision.",
          "数据飞轮把设计大模型插件的用户转化为数据，再由数据优化模型。直接提取的数据包括产品浏览量、使用次数、重复 input 率、output 结果选择率与选择时间、修改率与修改步数；间接提取的包括收藏量、点赞量、不喜欢量、人工评论与 A/B 测试。数据要求成本较低、数据量较高，并具备有效的模型优化能力。"),
        sl("gdm", [16,17,18])),
      S2("future", T("Future work", "04 未来展望"),
        T("Four threads remain open: supervised fine-tuning, reinforcement learning, multimodal generation and intelligent interaction. Nearer term, annotation needs completing and rendering rules need unifying — default styles, text formats and icon lookup — since annotation precision and render fidelity depend on each other.",
          "四条线索仍在继续：SFT、强化学习、多模态生成与智能交互。更近期的工作是完善标注与统一渲染规则——包括每种组件的默认样式、文字格式与 ICON 库搜索——因为标注精度与渲染还原度息息相关。"),
        sl("gdm", [19,20])),
    ],
  },

  wanderland: {
    source: T("Project boards, 4 panels", "项目展板，4 张"),
    parts: [
      S2("bg", T("Background & ideation", "Background & Ideation"),
        T("The boards open on the problem and the research behind it, using Kano analysis to sort which features would actually be felt, then move into ideation.",
          "展板从问题与背景研究开始，用 Kano 模型分析哪些功能真正会被用户感知，再进入概念发想。"),
        sl("wanderland", [1,2])),
      S2("structure", T("Story board & information architecture", "Story Board & 信息架构图"),
        T("A story board sets the everyday scenario, and the information architecture maps how animal information, discovery and community fit into one structure.",
          "故事板设定日常使用情境，信息架构图则梳理动物信息、内容发现与社区如何组织在同一结构中。"),
        sl("wanderland", [3])),
      S2("features", T("Map, animal information & community", "地图 · 动物信息 · 社区"),
        T("The final screens cover the map and personal centre, animal information, the community, and the technical support behind them.",
          "最终界面覆盖地图与个人中心、动物信息、社区，以及背后的技术支持。"),
        sl("wanderland", [4])),
    ],
  },

  philips: {
    source: T("Internship boards, 3 panels · watermarked public material", "实习展板，3 张 · 已加水印的公开素材"),
    parts: [
      S2("modes", T("Five smart shaving modes", "五重智能剃须模式"),
        T("The internship ran from July to October 2023 on the UI/UX of a new shaver, built around five smart shaving modes — regular, boost, gentle, deep and custom — so that customisation meets different needs.",
          "实习自 2023 年 7 月至 10 月，参与新一代剃须刀的 UI/UX 设计，围绕常规、增强、柔和、深剃、定制五重智能剃须模式展开，以定制化满足不同需求。"),
        sl("philips", [1])),
      S2("ui", T("Interface design & iteration", "界面设计与迭代"),
        T("Many sets of interface proposals were made and compared for how clearly the modes are distinguished and how they are operated, converging on the version that shipped.",
          "制作并比较了多组界面方案，围绕模式之间的区分度与操作方式反复迭代，最终收敛到上市版本。"),
        sl("philips", [2])),
      S2("testing", T("User testing", "用户测试"),
        T("A reactive feedback quantile test with participants produced the test results that fed back into the interface, and taught me most about pacing and information prompts.",
          "以 Reactive Feedback Quantile Test 与参与者开展用户测试，测试结果反馈回界面设计，也让我对交互节奏与信息提示的理解最为深入。"),
        sl("philips", [3])),
    ],
  },
};

Object.keys(PARTS).forEach(k => {
  if (!PROJECTS[k]) { console.warn("unknown project in PARTS: " + k); return; }
  PROJECTS[k].source = PARTS[k].source;
  PROJECTS[k].parts = PARTS[k].parts;
});

const HALLS = [
  {
    id: "research", num: "I",
    name: T("Interaction Design Research", "交互设计研究"),
    note: T("Three studies in which research, prototype and evidence had to hold each other up: language made tangible, expression made practisable, pain made speakable.",
            "三项研究：研究、原型与证据必须互相支撑——让语言有形，让表情可练习，让疼痛可被说出。"),
    projects: ["talevision", "mirrorcle", "hermoony"],
  },
  {
    id: "commercial", num: "II",
    name: T("AI+ Commercial Products", "AI+ 商业产品"),
    note: T("Products made inside real constraints — a market, a team, an existing platform — where the design judgement has to survive contact with a shipping schedule.",
            "在真实约束中完成的产品——市场、团队与既有平台——设计判断必须经得起交付节奏的检验。"),
    projects: ["huizhangbao", "travelshu", "gdm"],
  },
  {
    id: "early", num: "III",
    name: T("Early Works", "早期作品"),
    note: T("Earlier rooms of the archive: a health service, an interest community, and an internship inside an existing product framework.",
            "档案中较早的展厅：一项健康服务、一个兴趣社区，以及一段在既有产品框架内的实习。"),
    projects: ["opencare", "wanderland", "philips"],
  },
];

const UI = {
  museum: T("The Hantian Wu Museum", "吴晗天美术馆"),
  museumMark: T("Hantian Museum", "晗天美术馆"),
  backToHallShort: T("Back", "返回"),
  museumSub: T("Product & Interaction Design · Archive of nine works", "产品与交互设计 · 九件作品档案"),
  name: T("Hantian Wu", "吴晗天"),
  statement: T("Technology should feel more human.", "让科技温柔落地"),
  statementBody: T("A human-centred product and interaction designer working across AI, health and inclusive design. Designing products and interactions worth using, with evidence, empathy, and a little curiosity.",
                   "以人为本的产品与交互设计师，关注 AI、健康和包容性设计。用证据、同理心与一点点好奇，设计值得被使用的产品与交互。"),
  lobbyKicker: T("Entrance hall", "入口大厅"),
  plan: T("Plan of the galleries", "展厅平面"),
  enterHall: T("Enter hall", "进入展厅"),
  works: T("works", "件作品"),
  cue: T("Step closer", "走近观看"),
  cueLong: T("Click the wall to step closer", "点击墙面走近观看"),
  wallLabel: T("Wall label", "展签"),
  backToLobby: T("Lobby", "大厅"),
  backToHall: T("Back to hall", "返回展厅"),
  enterCase: T("Enter", "进入"),
  enterCaseNote: T("Read the full case study", "阅读完整案例"),
  credits: T("Credit line", "作品信息"),
  role: T("Role", "我的角色"),
  year: T("Year", "年份"),
  collab: T("Collaboration", "协作方式"),
  methods: T("Methods", "方法与技能"),
  results: T("Key results", "关键结果"),
  contents: T("Contents", "案例目录"),
  visitors: T("Visitors at this wall", "此墙前的观众"),
  nextWork: T("Next work", "下一件作品"),
  prevWork: T("Previous work", "上一件作品"),
  allHalls: T("All halls", "全部展厅"),
  closing: T("Please use the contact details provided with this portfolio.", "欢迎通过随本作品集提供的联系方式与我联系。"),
  copyright: T("© 2026 Hantian Wu. Built with research and empathy.", "© 2026 吴晗天. 以研究与同理心构建体验。"),
  imagePending: T("image to place", "待放置图像"),
  hallOf: T("Hall", "展厅"),
  slidesFrom: T("From the source document", "来自源文件"),
  slideCount: T("slides", "页"),
  swipeHint: T("Scroll or drag sideways", "左右滑动查看"),
  prevSlide: T("Previous slide", "上一页"),
  nextSlide: T("Next slide", "下一页"),
  codeFrom: T("From the technical document", "来自技术文档"),
  filmFrom: T("Film", "影像"),
  fullSize: T("View full size", "查看原始尺寸"),
  closeFull: T("Close", "关闭"),
  clickToEnlarge: T("Click a slide to view it full size", "点击页面查看原始尺寸"),
  entranceKicker: T("The museum is open", "开馆中"),
  open: T("Open the doors", "推门进入"),
  concourse: T("Concourse", "中央大厅"),
  concourseNote: T("Three halls open off the concourse. Step through a doorway.", "三个展厅由中央大厅通往，穿过门洞进入。"),
  doorCue: T("Step through", "穿门进入"),
  backToEntrance: T("Entrance", "入口"),
  backToConcourse: T("Concourse", "中央大厅"),
};

window.MUSEUM_CONTENT = { PROJECTS, HALLS, UI };
})();
